# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterselect',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Slug'),
        ),
    ]
