# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('metakey', models.CharField(max_length=250)),
                ('metadesc', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('published', models.IntegerField()),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('lft', models.IntegerField()),
                ('rght', models.IntegerField()),
                ('tree_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('one', models.CharField(max_length=250)),
                ('name2', models.CharField(max_length=250)),
                ('low_price', models.IntegerField(blank=True, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('ak', models.IntegerField(blank=True, null=True)),
                ('count_prod', models.IntegerField(blank=True, null=True)),
                ('reit', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('count_votes', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('pattern_title', models.CharField(max_length=250)),
                ('pattern_date', models.TextField()),
                ('pattern_key', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'shop_category',
                'managed': False,
            },
        ),
    ]
