# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date'),
        ),
    ]
