# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Scrapy Url'),
        ),
    ]
