# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.BooleanField(default=False, help_text='Show this product on Home page?', verbose_name='Published'),
        ),
    ]
