# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sky',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Sky'),
        ),
    ]
