# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170613_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
